import { Department, Doctor, Patient, Document, Note } from '../types';

export const departments: Department[] = [
  {
    id: 'dept1',
    name: 'Cardiology',
    code: 'CARD-01',
    floor: '3rd Floor',
    hodId: 'd1',
    hodName: 'Dr. Sarah Johnson',
    totalBeds: 50,
    availableBeds: 12,
    icuSlots: 10,
    description: 'Expert care for all heart-related conditions and diseases.',
  },
  {
    id: 'dept2',
    name: 'Neurology',
    code: 'NEUR-02',
    floor: '4th Floor',
    hodId: 'd2',
    hodName: 'Dr. Michael Chen',
    totalBeds: 40,
    availableBeds: 8,
    icuSlots: 5,
    description: 'Specialized treatment for brain and nervous system disorders.',
  },
  {
    id: 'dept3',
    name: 'Pediatrics',
    code: 'PEDI-03',
    floor: '2nd Floor',
    hodId: 'd3',
    hodName: 'Dr. Emily Brown',
    totalBeds: 60,
    availableBeds: 25,
    icuSlots: 8,
    description: 'Comprehensive medical care for children from birth through adolescence.',
  },
];

export const doctors: Doctor[] = [
  {
    id: 'd1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@apexcare.com',
    specialization: 'Cardiology',
    subSpecialization: 'Interventional Cardiology',
    qualifications: ['MD', 'PHD', 'FACC'],
    experience: 15,
    registrationNumber: 'MED-12345',
    primaryDepartmentId: 'dept1',
    consultationFee: 1500,
    followUpFee: 800,
    status: 'Available',
    availability: [
      { day: 'Monday', startTime: '09:00', endTime: '17:00', duration: 30 },
      { day: 'Wednesday', startTime: '09:00', endTime: '17:00', duration: 30 },
    ],
  },
  {
    id: 'd2',
    name: 'Dr. Michael Chen',
    email: 'michael.chen@apexcare.com',
    specialization: 'Neurology',
    subSpecialization: 'Neuro-Oncology',
    qualifications: ['MD', 'MS'],
    experience: 12,
    registrationNumber: 'MED-67890',
    primaryDepartmentId: 'dept2',
    consultationFee: 1800,
    followUpFee: 1000,
    status: 'Busy',
    availability: [
      { day: 'Tuesday', startTime: '10:00', endTime: '18:00', duration: 45 },
      { day: 'Thursday', startTime: '10:00', endTime: '18:00', duration: 45 },
    ],
  },
];

export const patients: Patient[] = [
  {
    id: 'p1',
    mrn: 'MRN-1001',
    name: 'John Smith',
    dob: '1985-05-12',
    gender: 'Male',
    bloodGroup: 'O+',
    phone: '+1 (555) 123-4567',
    email: 'john.smith@example.com',
    address: '123 Pine St, Cityville',
    emergencyContact: 'Jane Smith (+1 555-987-6543)',
    insuranceInfo: 'BlueCross BC-9921',
    status: 'Stable',
    assignedDoctorId: 'd1',
  },
  {
    id: 'p2',
    mrn: 'MRN-1002',
    name: 'Alice Williams',
    dob: '1992-08-24',
    gender: 'Female',
    bloodGroup: 'A-',
    phone: '+1 (555) 234-5678',
    email: 'alice.w@example.com',
    address: '456 Oak Lane, Townsville',
    emergencyContact: 'Bob Williams (+1 555-876-5432)',
    insuranceInfo: 'UnitedHealth UH-4432',
    status: 'In Treatment',
    assignedDoctorId: 'd2',
  },
  {
    id: 'p3',
    mrn: 'MRN-1003',
    name: 'Robert Davis',
    dob: '1970-11-03',
    gender: 'Male',
    bloodGroup: 'B+',
    phone: '+1 (555) 345-6789',
    email: 'robert.d@example.com',
    address: '789 Maple Rd, Village',
    emergencyContact: 'Mary Davis (+1 555-765-4321)',
    insuranceInfo: 'Aetna AE-1122',
    status: 'Critical',
    assignedDoctorId: 'd1',
  },
];

export const documents: Document[] = [
  {
    id: 'doc1',
    applicationId: 'APP-90210',
    type: 'MRI',
    patientId: 'p1',
    patientName: 'John Smith',
    patientMrn: 'MRN-1001',
    uploadDate: '2024-04-20',
    thumbnail: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=200&h=150&fit=crop',
    fileUrl: '#',
    notes: 'Mild inflammation detected in the thoracic region.',
    filesCount: 3,
    latestActivity: 'Viewed 2h ago',
    uploadedBy: 'Dr. Sarah Johnson',
  },
  {
    id: 'doc2',
    applicationId: 'APP-88432',
    type: 'Blood Test',
    patientId: 'p1',
    patientName: 'John Smith',
    patientMrn: 'MRN-1001',
    uploadDate: '2024-04-22',
    thumbnail: 'https://images.unsplash.com/photo-1579152276506-2d50148bee3a?w=200&h=150&fit=crop',
    fileUrl: '#',
    notes: 'Hemoglobin levels slightly low.',
    filesCount: 1,
    latestActivity: 'Uploaded',
    uploadedBy: 'Lab Technician',
  },
];

export const notes: Note[] = [
  {
    id: 'n1',
    patientId: 'p1',
    authorId: 'd1',
    authorName: 'Dr. Sarah Johnson',
    content: 'Patient responded well to the new medication. Monitor blood pressure daily.',
    createdAt: '2024-04-25T10:30:00Z',
  },
];
